PROJECT_NAME: "MaskRCNN"

CONFIG_NAME: "lars-16-cosineannealinglrwarmuprestarts-gamma0.5-1e-3"

EPOCHS: 10

SCHEDULER:
  NAME: "cosineannealinglrwarmuprestarts"
  WARMUP_ITERS: 1
  MAX_ITER: 10
  GAMMA: 0.5

DATASET:
  ASPECT_RATIO_GROUP_FACTOR: 2

OPTIMIZER:
  NAME: "lars"
  LR: 0.001
