PROJECT_NAME: "MaskRCNN"

CONFIG_NAME: "lars-16-multistep-gamma0.75-3step"

EPOCHS: 10

SCHEDULER:
  STEPS: (3,5,8)
  WARMUP_ITERS: 1
  GAMMA: 0.75

DATASET:
  ASPECT_RATIO_GROUP_FACTOR: 2

OPTIMIZER:
  NAME: "lars"
  LR: 0.001
