PROJECT_NAME: "MaskRCNN"

CONFIG_NAME: "multi-p3.16xlarge-1"

EPOCHS: 10
NUM_NODES: 2

SCHEDULER:
  NAME: "cosineannealinglrwarmup"
  WARMUP_ITERS: 1
  MAX_ITER: 10

DATASET:
  ASPECT_RATIO_GROUP_FACTOR: 2

OPTIMIZER:
  NAME: "lars"
  LR: 0.0008

DATALOADER:
  TRAIN_BATCH_SIZE: 8
