PROJECT_NAME: "MaskRCNN"

CONFIG_NAME: "sgd-16-cosineannealinglrwarmup-2e-2"

EPOCHS: 10

SCHEDULER:
  NAME: "cosineannealinglrwarmup"
  WARMUP_ITERS: 1
  MAX_ITER: 10

DATASET:
  ASPECT_RATIO_GROUP_FACTOR: 2

OPTIMIZER:
  NAME: "sgd"
  LR: 0.02
