PROJECT_NAME: "MaskRCNN"

CONFIG_NAME: "lars-16-polynomial2-3e-4"

EPOCHS: 10

SCHEDULER:
  NAME: "polynomial"
  MAX_ITER: 10
  GAMMA: 2.0

DATASET:
  ASPECT_RATIO_GROUP_FACTOR: 2

OPTIMIZER:
  NAME: "lars"
  LR: 0.00033
